timezone=America/Mexico_City
server.port=8080

# Configuración de la base de datos
spring.datasource.url=
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City
spring.jpa.hibernate.ddl-auto=none

google.recaptcha.secret=6LcYneEqAAAAAInKlcBr0T2Jq55xteS-E_i_nJMQ

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

# swagger-ui custom path
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.api-docs.path=/api/v3/api-docs

jwt.secret=LhSOEJXHmM3qDFifzXpMnFFyjpyfIQbApdGoPCBZRsGKEEzE43iXC1rXjuqfCSMi73Qsv9LTFOa9t5VSzsK33P7h3XxoTNAlQnQh2eZYtrmzWCITJIs09UrbrVexqXGtqqjCHjqojVJrb47E6yIwltKfBph8VoyFuYNKKtgLujq40rkP6C6
jwt.sessionLifetime=28800
rsa.private_key_pem=-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfNY10LIMokgRPyG23Ucu3kp+sdBzKn705w6xA2hq958KTHUsvnDzqOPZscM9lbaJh570qg7S+lgW36eBhdQwLv28zQ0T4RDxxtIW7YmfkJDLG7aA1e8HKjrbfOqrffcGI8G+n5PJW/1j3wCA0NbTWKXoyCWHLFiaim4W6KWQclZ9wE3qhg4q2VUCUmkzAqzw5cpvMu7X1t1fqRKcmzK+T48188RKcSI7xrDmaqy7DyHO0CyzbUZYq9yg5GTkdeXlqeMUjTUcAXIT72mAQenMKmK5k/4XGJ67MFmOq13IkWblMgDhpA3AlOblwRywXO879MpTQr05hvRsIO8l4A5vTAgMBAAECggEAA3oAy3Txxw/rmy7Mj1bwavyyX7dhx5G8aPrOYKFcOYhj9dPYB/afJLUD7VmufByfeDukvfBsh0exLhM9cwAo0eFAyHt83pHMfH+NXT2okh4X1vZqa+PDcOAAu0tfK6X/dQH3FjeU8sEwGRAV3YrMsGtTphMRX4UHNY00dHYh7J1vZDU1/Za7BCqcTJ/aD3hx6mNWkJV4qIk0zpEcTzd9sfXVgaKhMlomS8fVLvoipT8c9tDGsd0AT4LpDb2SlkaDLLRZCLjMtO9juaSdK4Tntdm3zjQ1O8js+693cjzGxxaHRIWEYP7wr4FvyeXO1197XFT71Ug99wlHwVztd+uXKQKBgQDPRbTBJ0pJ1X9NqIzFl2fI3yUDi5NLxqr4TGDr2vaTw6WVLv6GMaHUtLa5gEbxvOK6TKKDPnUlsUTS6pe0fPd2yDwQREAkvVTmYXuz5t2EjJD+wYA+4Db9pWIc71gQGCpgAbrjlxisNYV4kg+M2xISz0dKE2H7/mdWc30WHK9rmQKBgQDEo0JM3AiGUkLJpb4WrOKIuTDtnR2H93CYHOlaUZQUpiDxVDzZ1zB+rrSt8vrs+tkX2WdtKTa1ZZqw6++9t8xvSNPEQryqvl7ZpYZvmsdyaKqROX0NVba9UDI9hOqMoNFs0TRUEPzoUCLbplEbHXr6VsAP5JbaMz46dRp/eNWGSwKBgCWUM8NZRkTAqoX/6xXf73chzeooohn4+QJvhpr8ZfxAWoMDtC3MTdTstrxHH5Wwc0Lnpgc5ia+9xgafdcXJamxkvU8NsLt4gC4MuorRbpQbkCZAGupLaGzwUSuB0WuJlhU1+xZMTLLcOUi04pDdHxe98OTjQr6XT1EDO0iJBtzxAoGBALEMTiXl98b5SilFkmHYSB/SnrtTO8OwhzBu16z6xtnQutiPgDqkBoYJx6TXoha9xbozhWxEL34kfaPOy42GcAvDBukvLbCOt9g/sUvLkMjydKFNocrf4imSi6nYg1cbdXUE6JjIsu55OOmMVnqTkKbWdRfaOfk9Kkp4JeOgaKEBAoGAGodItNU/AkgmYlxgmE8JplfdgIVx/Lgvysd5NbjCnPOIE5d/nmCyA4LCfyM1WEexVXtnJij6weyymLfFaIrR4Eg4HXl3gnaGuWYOsCspNB0MfCbhmRKqYi+Y0IgTeggKInmW0lwS7zE+lkqzBrMvO6efd5t5Nuh3/Bg8zdaKRoI=-----END PRIVATE KEY-----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
#Maximo del archivo para cada request
spring.servlet.multipart.max-file-size=5MB
#Maximo del multipart
spring.servlet.multipart.max-request-size=5MB
file-constraint.upload.validator=5242880

spring.jackson.time-zone=America/Mexico_City
