timezone=America/Mexico_City
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tazuyuti?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=takerwells
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City
spring.jpa.hibernate.ddl-auto=none

jwt.secret=LhSOEJXHmM3qDFifzXpMnFFyjpyfIQbApdGoPCBZRsGKEEzE43iXC1rXjuqfCSMi73Qsv9LTFOa9t5VSzsK33P7h3XxoTNAlQnQh2eZYtrmzWCITJIs09UrbrVexqXGtqqjCHjqojVJrb47E6yIwltKfBph8VoyFuYNKKtgLujq40rkP6C6
jwt.sessionLifetime=28800
rsa.private_key_pem=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3ik6YFoaRpm+PAiMgogswWAfsA/xGb2lOHF4ngLkaPA7R6HgbJ/HXpX+X2dkP08nV5L5/IarapDDyvGjrIAemr5MEzkjNrznGxHpS2q22jZgtJqqwwqflfysnvG1n6RWjaSBxwusduunrcvJvAMtP1aXor3Hc9sio15fCgg64VzkjVRc/sukb+jF+7jeSAgPsfYqY+vu03YGuLZQeJYMpamIOeBFeKKKr0TTyyBklJkqLgjFnAVQGnQxJ0AUqfucr91fntel/jMk9A85nY+bgJxn/UROLTVyC4z13GF3+DYJQDc11Q72r3mO0cKu6KVURcvLJkwkzEFFX4ngif+91AgMBAAECggEANbZA99snuHoXjadXdlZVpektMFGeQ1KZY6WDnFXcVaQbxiwc8f2Hlc81/s9e6XXWTEUrxnKo2GFSfcbLgXuXIZ2iDbb8sUzFQLkA/zxFt/XKAfSd4SqmDdBgZbmL3uvkTDUYrJIZUlL/38p8ziVSWmOwsN6fGMYTxO2K2P5Mpn9IPU+tUDDgCd2Q0BwDwIHf8Z6wFXcCLvZhQG/AtxfGvChcxYDdiAHTz3cl3efpTHjVPZrG/u3uyCGB9qzZ5BEGL6lwi/PcYavPwTJf/prJTqBTygae1yCkuDv+XyBS8fwx5s/r47PHe4fl38VbbpU+ZkyTU3MJ5uHLgC6JJk28xQKBgQD1Yx+wcbXoXRUQ9lqhx5UJ7q4yh4ppbo2uQ6XoMPA6Evmwh4PxpOLJfW34kyOzTwX6CaWObtf1LnIrejmpIrI7aAnJ1CKCLzeJUYolzpogKYzD+tuYih/bYTeMmPhhT+D+GqS5ABzrIfrJRFor5l3pnUMxlF5WnAbJTIw5h6I55wKBgQC/em09sdyXUFbh6Mprl0gJakDirzKdbxUNUmkCZYUU7MDZR3LxMczFjksIFsrIofleegor9o+Q7MyuOEOpV8E3DiJUdih+2jpZETVGSiG6GA+eZgbeMkqr9A0faeUs0n3jDxdGQByD7bMogRp5a84hLb/1GrEmKE6MaMxzDRX4QwKBgDObaDO8hmxa/y41EXSKu+590wbveI2Z4ZQvx/mgKTWdfgPBTF+KtON5TKKFl3GDghdG5hmheCupW/uG1g+bK27Q/5YB1kwY0A5CJtKys7ll46Pn4z0ed3q05HDeTwZwPTpTsibyPiK5X7vqcyheZ4vVNid8M6b1Y3v8bFVBED4rAoGAE3kW7QROo9DW1SjAlUqQV+zHZoZcxmgKow0zgrviWett/WrnxKHE6n57IPp4awkV/Ea7DBeKKDn84ubz8p/rFXdJhH9zxNravj4ixeA6J9vUks5benNw5qXuQ7iYRwOtK89YFZvlioE9DCx9DcYp83PcpsetJm1I97yctkKpblMCgYEAqmFplriwDmnC4Y+dIrmOfRmSB35z1JsaowUWoiG+8r5MG0H95MWsUCeCt4A6BOpJgNyZEzWdxYH8x2pMOwLAcFIj4xtmUZS3Q+p79jwax9pwEgRGwFhGmMTOhko/5cj/LhFOJjF0wyFetCQlhdfIDZIvUgSjXiu+oSq37HNOWo8=
    
google.recaptcha.secret=6LcYneEqAAAAAInKlcBr0T2Jq55xteS-E_i_nJMQ

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

# swagger-ui custom path
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.api-docs.path=/api/v3/api-docs

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
#Maximo del archivo para cada request
spring.servlet.multipart.max-file-size=5MB
#Maximo del multipart
spring.servlet.multipart.max-request-size=5MB
file-constraint.upload.validator=5242880

spring.jackson.time-zone=America/Mexico_City
files.upload-directory-documento=uploads/documentos/
