/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 23 Feb 2025
 * @date 23/02/2025
 */
package com.example.residencia_back.entities.administration;

import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onUpdate;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a user entity in the administration schema, mapping to the "usuarios" table.
 *
 * @param id                  The unique identifier of the user (automatically generated).
 * @param activo              Indicates if the user is active (default is true).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "administracion", name = "usuarios")
public class UserActive {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ACTIVO_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.User.ENTITY_ACTIVE, example = "false")        // This annotation indicates that information for the swagger
    @Column(name = "activo", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Boolean activo = true;

}
