/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 03 Jun 2025
 * @date 03/06/2025
 */
package com.example.residencia_back.entities.administration;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.sql.Timestamp;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;

/**
 * Represents a user entity in the administration schema, mapping to the
 * "usuarios" table.
 *
 * @param id The unique identifier of the user (automatically generated).
 * @param nombre The first name of the user (required, 5-40 characters).
 * @param apellidoPaterno The last name of the user (required, 5-40 characters).
 * @param apellidoMaterno The second last name of the user (optional, 5-40
 * characters).
 * @param correoPersonal The personal email of the user (required, unique, must
 * be a valid email format).
 * @param usuario The username of the user (required, max 50 characters).
 * @param contrasenia The password of the user (required, ignored in JSON
 * responses).
 * @param cargo The position or title of the user within the organization
 * (required, 5-50 characters).
 * @param telefono The user's phone number (optional, 7-10 characters).
 * @param extension The phone extension number (optional, 4-6 characters).
 * @param celular The user's cell phone number (required, 7-10 characters).
 * @param rol The role assigned to the user (required, maps to "rol_id").
 * @param fecha_creacion The timestamp indicating when the user was created
 * (automatically generated).
 * @param fecha_actualizacion The timestamp indicating when the user was last
 * updated (optional).
 * @param activo Indicates if the user is active (default is true).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "administracion", name = "usuarios")
public class User {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_NOMBRE_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.User.ENTITY_NOMBRE, example = "Juan")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_NOMBRE_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_NOMBRE_REQUERIDO)
    @Column(name = "nombre", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String nombre;

    @Schema(description = SystemText.User.ENTITY_APELLIDO_PATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_APELLIDO_PATERNO_REQUERIDO)           // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_APELLIDO_PATERNO_REQUERIDO)
    @Column(name = "apellido_paterno", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoPaterno;

    @Schema(description = SystemText.User.ENTITY_APELLIDO_MATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_APELLIDO_MATERNO_REQUERIDO)
    @Column(name = "apellido_materno", length = 50, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoMaterno;

    @Schema(description = SystemText.User.ENTITY_CORREO_PERSONAL, example = "juan.torres@gmail.com")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @NotBlank(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_REQUERIDO)        // This annotation indicates that this parameter must not be empty.
    @Email(groups = {onCreate.class, onUpdate.class}, flags = {Pattern.Flag.CASE_INSENSITIVE}, regexp = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_INVALIDO)
    @Column(name = "correo_personal", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String correoPersonal;

    @Column(name = "usuario", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String usuario;

    @Column(name = "contrasenia", length = 128, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String contrasenia;

    @Schema(description = SystemText.User.ENTITY_CARGO, example = "Capturista")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_CARGO_REQUERIDO)          // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 5, max = 100, message = SystemText.User.ENTITY_USUARIO_CARGO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_CARGO_REQUERIDO)
    @Column(name = "cargo", length = 100, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String cargo;

    @Schema(description = SystemText.User.ENTITY_TELEFONO, example = "5178765")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_TELEFONO_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 7, max = 10, message = SystemText.User.ENTITY_USUARIO_TELEFONO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "telefono", length = 10, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String telefono;

    @Schema(description = SystemText.User.ENTITY_EXTENSION, example = "567")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 10, message = SystemText.User.ENTITY_USUARIO_EXTENSION_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "extension", length = 10, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String extension;

    @Schema(description = SystemText.User.ENTITY_CELULAR, example = "9514567656")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 10, max = 10, message = SystemText.User.ENTITY_USUARIO_CELULAR_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "celular", length = 10, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String celular;

    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_ROL_REQUERIDO)            // This annotation indicates that this parameter must not be null.
    @OneToOne               // This annotation indicates that it has a one-to-one relationship with the assigned table.
    @JoinColumn(name = "rol_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private Role rol;

    @JsonIgnore                         // This annotation indicates that the attribute will not be displayed in the returned json
    @CreationTimestamp                  // This annotation indicates that the field is automatically set to the creation date and time.
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_creacion", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fecha_creacion;

    @JsonIgnore                         // This annotation indicates that the attribute will not be displayed in the returned json
    @Temporal(TemporalType.TIMESTAMP)   // This annotation indicates that the field stores date and time.
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_actualizacion", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fecha_actualizacion;

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "activo", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Boolean activo = true;

}
