/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 02 Ene 2025
 * @date 02/01/2025
 */
package com.example.residencia_back.entities.administration;

import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.sql.Timestamp;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;

/**
 * Represents a user entity in the administration schema, mapping to the "usuarios" table.
 *
 * @param id                  The unique identifier of the user (automatically generated).
 * @param nombre              The first name of the user (required, 5-40 characters).
 * @param apellidoPaterno     The last name of the user (required, 5-40 characters).
 * @param apellidoMaterno     The second last name of the user (optional, 5-40 characters).
 * @param correo      The personal email of the user (required, unique, must be a valid email format).
 * @param usuario             The username of the user (required, max 50 characters).
 * @param contrasenia         The password of the user (required, ignored in JSON responses).
 * @param telefono            The user's phone number (optional, 7-10 characters).
 * @param fecha_creacion      The timestamp indicating when the user was created (automatically generated).
 * @param activo              Indicates if the user is active (default is true).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "administracion", name = "usuarios")
public class User {
     @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_NOMBRE_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.User.ENTITY_NOMBRE, example = "Juan")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_NOMBRE_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_NOMBRE_REQUERIDO)
    @Column(name = "nombre", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String nombre;

    @Schema(description = SystemText.User.ENTITY_APELLIDO_PATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_APELLIDO_PATERNO_REQUERIDO)           // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_APELLIDO_PATERNO_REQUERIDO)
    @Column(name = "apellido_paterno", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoPaterno;
    
    @Schema(description = SystemText.User.ENTITY_APELLIDO_MATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 50, message = SystemText.User.ENTITY_USUARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.User.ENTITY_USUARIO_APELLIDO_MATERNO_REQUERIDO)
    @Column(name = "apellido_materno", length = 50, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoMaterno;
    
    @Schema(description = SystemText.User.ENTITY_CORREO_PERSONAL, example = "juan.torres@gmail.com")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @NotBlank(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_REQUERIDO)        // This annotation indicates that this parameter must not be empty.
    @Email(groups = {onCreate.class, onUpdate.class}, flags = {Pattern.Flag.CASE_INSENSITIVE}, regexp = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message = SystemText.User.ENTITY_USUARIO_EMAIL_PERSONAL_INVALIDO)
    @Column(name = "correo", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String correo;
    
    @Column(name = "usuario", length = 50, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String usuario;
    
    @JsonIgnore                 // This annotation indicates that the attribute will not be displayed in the returned json
    @Column(name = "contrasenia", length = 128, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    private String contrasenia;
    
    @Schema(description = SystemText.User.ENTITY_TELEFONO, example = "5178765")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_USUARIO_TELEFONO_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 7, max = 10, message = SystemText.User.ENTITY_USUARIO_TELEFONO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "telefono", length = 10, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String telefono;

    @JsonIgnore                         // This annotation indicates that the attribute will not be displayed in the returned json
    @CreationTimestamp                  // This annotation indicates that the field is automatically set to the creation date and time.
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_creacion", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fecha_creacion;

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "activo", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Boolean activo = true;
}
