/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 03 Jun 2025
 * @date 03/06/2025
 */
package com.example.tazuyuti_back.entities.modules;

import java.sql.Timestamp;

import org.hibernate.annotations.CreationTimestamp;

import com.example.tazuyuti_back.entities.administration.User;
import com.example.tazuyuti_back.helpers.SystemText;
import com.example.tazuyuti_back.validator.onCreate;
import com.example.tazuyuti_back.validator.onUpdate;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "entregar_paquete")
public class EntregarPaquete {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @Schema(description = "observaciones", example = "Mi carro")        // This annotation indicates that information for the swagger
    @Column(name = "observaciones", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String observaciones;

    @Schema(description = "recibio", example = "Mi carro")        // This annotation indicates that information for the swagger
    @Column(name = "recibio", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String recibio;

    @ManyToOne
    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "El Usuario es requerido")            // This annotation indicates that this parameter must not be null.
    @JoinColumn(name = "usuario_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private User usuario;

    @CreationTimestamp
    @Schema(hidden = true)
    @Column(name = "fecha   ", nullable = false)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    private Timestamp fecha;

    @OneToOne
        @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "El Usuario es requerido")            // This annotation indicates that this parameter must not be null.
    @JoinColumn(name = "paquete_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private Paquete paquete;

}
