/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 03 Jun 2025
 * @date 03/06/2025
 */
package com.example.tazuyuti_back.entities.modules;

import java.sql.Timestamp;
import java.util.List;

import org.hibernate.annotations.CreationTimestamp;
import com.example.tazuyuti_back.entities.administration.User;
import com.example.tazuyuti_back.entities.catalogs.EstadoPaquete;
import com.example.tazuyuti_back.entities.catalogs.Sucursal;
import com.example.tazuyuti_back.helpers.SystemText;
import com.example.tazuyuti_back.validator.onCreate;
import com.example.tazuyuti_back.validator.onUpdate;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "paquete")
public class Paquete {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "destinatario es requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "destinatario", example = "Jonathan")        // This annotation indicates that information for the swagger
    @Column(name = "destinatario", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String destinatario;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "remitente es requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "remitente", example = "Jonathan")        // This annotation indicates that information for the swagger
    @Column(name = "remitente", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String remitente;

    @CreationTimestamp
    @Schema(hidden = true)
    @Column(name = "fecha_creacion", nullable = false)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    private Timestamp fechaCreacion;

    @ManyToOne
    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "El Usuario es requerido")            // This annotation indicates that this parameter must not be null.
    @JoinColumn(name = "usuario_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private User usuario;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "La forma de pago es requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "Nombre de la camioenta", example = "01 Efectivo")        // This annotation indicates that information for the swagger
    @Column(name = "forma_pago", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String formaPago;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "Total de la venta es requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "Total de la venta", example = "10.50")        // This annotation indicates that information for the swagger
    @Column(name = "total", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private double total;  

    @Schema(description = "Folio de la venta", example = "D58")        // This annotation indicates that information for the swagger
    @Column(name = "folio", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String folio;

    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @OneToOne               // This annotation indicates that it has a one-to-one relationship with the assigned table.
    @JoinColumn(name = "estado_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private EstadoPaquete estado;

    @Schema(description = SystemText.User.ENTITY_SUCURSAL_ID, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.User.ENTITY_SUCURSAL_ID_REQUERIDO)            // This annotation indicates that this parameter must not be null.
    @ManyToOne              // This annotation indicates that it has a one-to-one relationship with the assigned table.
    @JoinColumn(name = "destino_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private Sucursal destino;

        @Column(name = "pago", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private double pago;

    @Column(name = "cambio", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private double cambio;

    @Valid
    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @JsonManagedReference             
    @Schema(description = "Arreglo de los detalles de la venta")        // This annotation indicates that information for the swagger        // This annotation indicates that information for the swagger
    @OneToMany(mappedBy = "paquete", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<DetallePaquete> detallePaquete = null;
}
