/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.0 Creado el 03 Jun 2025
 * @date 03/06/2025
 */
package com.example.tazuyuti_back.entities.modules;

import java.time.LocalTime;
import com.example.tazuyuti_back.helpers.SystemText;
import com.example.tazuyuti_back.validator.onCreate;
import com.example.tazuyuti_back.validator.onUpdate;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "ruta")
public class Ruta {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.User.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.User.ENTITY_USUARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @ManyToOne
    @Schema(description = SystemText.User.ENTITY_ROL, example = "{ \"id\": 1 }")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "El Usuario es requerido")            // This annotation indicates that this parameter must not be null.
    @JoinColumn(name = "unidad_id", referencedColumnName = "id")                // This annotation indicates that Relate the table to another
    private Unidad unidad;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "viaje requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "viaje", example = "Oaxaca-Juxtlahuaca / Juxtlahuaca-Oaxaca")        // This annotation indicates that information for the swagger
    @Column(name = "viaje", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String viaje;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "repeticion requerido")         // This annotation indicates that this parameter must not be null.
    @Schema(description = "repeticion", example = "Lunes,Martes")        // This annotation indicates that information for the swagger
    @Column(name = "repeticion", nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String repeticion;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = "La hora es requerida")
    @Schema(description = "Hora de salida", example = "08:30:00")
    @Column(name = "hora", nullable = false)
    @JsonFormat(pattern = "HH:mm")
    private LocalTime  hora;

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @Column(name = "estado", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Boolean estado = true;
}
