/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.1 Modificado el 26 Feb 2025
 * @date 26/02/2025
 */
package com.example.residencia_back.entities.modules;

import java.sql.Timestamp;

import com.example.residencia_back.entities.catalogs.AssignmentArea;
import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a truck type entity in the modules schema, mapping to the
 * "tipo_camioneta" table.
 *
 * @param id The unique identifier of the truck type (automatically generated).
 * @param nombre The name of the truck type (required, non-nullable, max length: 30).
 * @param modelo The model of the truck type (required, non-nullable, max length: 30).
 * @param combustible The type of fuel associated with the truck (required, references Fuel entity).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "vehiculo")
public class Car {
     @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.Car.ENTITY_ID, example = "1")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.Car.ENTITY_VEHICULO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_NOMBRE_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_NOMBRE, example = "Vehiculo")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 80, message = SystemText.Car.ENTITY_VEHICULO_NOMBRE_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "nombre", length = 80, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String nombre;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_NUMERO_SERIE_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_VEHICULO_NUMERO_SERIE, example = "506-105")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 30, message = SystemText.Car.ENTITY_VEHICULO_NUMERO_SERIE_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "numero_serie", length = 30, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String numeroSerie;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_COLOR_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_VEHICULO_COLOR, example = "Blanco")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 20, message = SystemText.Car.ENTITY_VEHICULO_COLOR_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "color", length = 20, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String color;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_MARCA_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_VEHICULO_MARCA, example = "NISAn")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 20, message = SystemText.Car.ENTITY_VEHICULO_MARCA_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "marca", length = 20, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String marca;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_PLACAS_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_VEHICULO_PLACAS, example = "NISAn")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 20, message = SystemText.Car.ENTITY_VEHICULO_PLACAS_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "placas", length = 20, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String placas;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_VEHICULO_CDFI_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Car.ENTITY_VEHICULO_CDFI, example = "CDFI")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 20, message = SystemText.Car.ENTITY_VEHICULO_CDFI_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "cdfi", length = 20, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String cdfi;

    @Schema(description = SystemText.Car.ENTITY_VEHICULO_OBSERVACIONES, example = "Observaciones adicionales")        // This annotation indicates that information for the swagger
    @Column(name = "observaciones", length = 400, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String observaciones;

    @Temporal(TemporalType.TIMESTAMP)   // This annotation indicates that the field stores date and time.
    @Schema(hidden = true)              // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "cdfi_fecha", nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp cdfiFecha;

    @ManyToOne                  // This annotation indicates that Indicates that it is a foreign key
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_TIPO_CAMIONETA_ID_REQUERIDO)       // This annotation indicates that this parameter must not be empty.
    @Schema(description = SystemText.Car.ENTITY_TIPO_CAMIONETA_ID, example = "{\"id\": 1}")        // This annotation indicates that information for the swagger
    @JoinColumn(name = "tipo_camioneta_id", nullable = false, referencedColumnName = "id")
    private TruckType camionetaTipo;

    @ManyToOne                  // This annotation indicates that Indicates that it is a foreign key
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Car.ENTITY_AREA_ASIGNACION_ID_REQUERIDO)       // This annotation indicates that this parameter must not be empty.
    @Schema(description = SystemText.Car.ENTITY_AREA_ASIGNACION_ID, example = "{\"id\": 1}")        // This annotation indicates that information for the swagger
    @JoinColumn(name = "area_asignacion_id", nullable = false, referencedColumnName = "id")
    private AssignmentArea areaAsignacion;
}
