/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.1 Modificado el 26 Feb 2025
 * @date 26/02/2025
 */
package com.example.residencia_back.entities.modules;

import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a civil entity in the modules schema, mapping to the
 * "funcionario" table.
 *
 * @param id The unique identifier of the civil entity (automatically generated).
 * @param nombre The first name of the civil entity (required,
 * non-nullable, max length: 30).
 * @param apellidoPaterno The last name (paternal surname) of the civil entity 
 * (required, non-nullable, max length: 30).
 * @param apellidoMaterno The second last name (maternal surname) of the civil entity 
 * (optional, max length: 30).
 * @param telefono The phone number of the civil entity 
 * (required, non-nullable, max length: 10).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "funcionario")
public class Civil {
     @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.Civil.ENTITY_ID, example = "10")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.Civil.ENTITY_FUNCIONARIO_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Civil.ENTITY_FUNCIONARIO_NOMBRE_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.Civil.ENTITY_NOMBRE, example = "Juan")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 30, message = SystemText.Civil.ENTITY_FUNCIONARIO_NOMBRE_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.Civil.ENTITY_FUNCIONARIO_NOMBRE_REQUERIDO)
    @Column(name = "nombre", length = 30, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String nombre;

    @Schema(description = SystemText.Civil.ENTITY_APELLIDO_PATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Civil.ENTITY_FUNCIONARIO_APELLIDO_PATERNO_REQUERIDO)           // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 30, message = SystemText.Civil.ENTITY_FUNCIONARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.Civil.ENTITY_FUNCIONARIO_APELLIDO_PATERNO_REQUERIDO)
    @Column(name = "apellido_paterno", length = 30, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoPaterno;

    @Schema(description = SystemText.Civil.ENTITY_APELLIDO_MATERNO, example = "Torres")        // This annotation indicates that information for the swagger
    @Size(groups = {onCreate.class, onUpdate.class}, min = 2, max = 30, message = SystemText.Civil.ENTITY_FUNCIONARIO_APELLIDO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Pattern(groups = {onCreate.class, onUpdate.class}, regexp = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+|^$", message = SystemText.Civil.ENTITY_FUNCIONARIO_APELLIDO_MATERNO_REQUERIDO)
    @Column(name = "apellido_materno", length = 30, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String apellidoMaterno;
  
    @Schema(description = SystemText.Civil.ENTITY_TELEFONO, example = "5178765")        // This annotation indicates that information for the swagger
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.Civil.ENTITY_FUNCIONARIO_TELEFONO_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Size(groups = {onCreate.class, onUpdate.class}, min = 7, max = 10, message = SystemText.Civil.ENTITY_FUNCIONARIO_TELEFONO_TAMANIO_TEXTO)      // This annotation indicates that this parameter must meet certain minimum and maximum character limits.
    @Column(name = "telefono", length = 10, nullable = true)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String telefono;
}
