/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.1 Modificado el 26 Feb 2025
 * @date 26/02/2025
 */
package com.example.residencia_back.entities.modules;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import java.sql.Timestamp;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.web.multipart.MultipartFile;
import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.helpers.Anottation.FileConstraint;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Represents a file Tracking document entity in the "siac" schema, mapping to
 * the "archivos_documentos_peticion" table. This entity stores information
 * about a document related to a request, including its creation and update
 * timestamps, as well as the associated Tracking document and file data.
 *
 * @param id The unique identifier of the file Tracking document (automatically
 * generated).
 * @param peticion The associated BinnacleFuel  (foreign key to the "BinnacleFuel " entity).
 * @param nombreArchivo The name of the file (optional, max length: 150
 * characters).
 * @param documento The document description or name (optional, max length: 70
 * characters).
 * @param archivo The uploaded file data (not mapped to the database, used for
 * file uploads).
 * @param fechaCreacion The timestamp when the document was created
 * (automatically generated).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString // Exclude to avoid cycles
@Table(schema = "siac", name = "archivos_bitacora_combustible")
public class FilesBinnacleFuel {

    @Id                         // This annotation indicates that this field is the primary key of the entity.
    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = "ID del documento", example = "10")        // This annotation indicates that information for the swagger
    private int id = 0;

	@Builder.Default                    // This annotation indicates that the attribute has a default value
    @JsonBackReference                  // Indica el lado inverso de la relación bidireccional, omitiendo este campo en la serialización JSON para evitar la recursión infinita.
    @ManyToOne(fetch = FetchType.LAZY)                  // This annotation indicates that Indicates that it is a foreign key
    @JoinColumn(name = "bitacora_combustible_id", nullable = false, referencedColumnName = "id")            // This annotation indicates that Relate the table to another
    private BinnacleFuel bitacoraCombustible = null;

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "nombre_archivo", length = 150)       // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String nombreArchivo = "";

    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "documento", nullable = true, length = 70)       // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String documento = "";

    @JsonIgnore                 // This annotation indicates that the attribute will not be displayed in the returned json
    @Transient                  // This annotation indicates that the attribute will not be mapped in the database
    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @FileConstraint(maxSize = 5242880, allowedExtensions = ".*\\.(jpg|jpeg|png|pdf)", message = SystemText.General.ENTITY_FILECONSTRAINT_FILE_PDF_IMAGEN)
    private MultipartFile archivo = null;

    @JsonIgnore                 // This annotation indicates that the attribute will not be displayed in the returned json
    @Builder.Default                    // This annotation indicates that the attribute has a default value
    @CreationTimestamp          // This annotation indicates that the field is automatically set to the creation date and time.
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_creacion", nullable = true)       // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fechaCreacion = null;

}
