/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.1 Modificado el 26 Feb 2025
 * @date 26/02/2025
 */
package com.example.residencia_back.entities.modules;

import java.math.BigDecimal;
import java.sql.Timestamp;

import org.hibernate.annotations.CreationTimestamp;

import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a truck type entity in the modules schema, mapping to the
 * "tipo_camioneta" table.
 *
 * @param id The unique identifier of the truck type (automatically generated).
 * @param nombre The name of the truck type (required, non-nullable, max length: 30).
 * @param modelo The model of the truck type (required, non-nullable, max length: 30).
 * @param combustible The type of fuel associated with the truck (required, references Fuel entity).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "historial_tarjeta")
public class HistoryCard {
     @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.HistoryCard.ENTITY_ID, example = "1")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.HistoryCard.ENTITY_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @CreationTimestamp          // This annotation indicates that the field is automatically set to the creation date and time.
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_creacion", nullable = false)       // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fechaCreacion;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.HistoryCard.ENTITY_ANTES)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.HistoryCard.ENTITY_ANTES_REQUERIDO, example = "30.50")        // This annotation indicates that information for the swagger
    @Column(name = "antes", nullable = false) 
    private BigDecimal antes;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.HistoryCard.ENTITY_DESPUES)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.HistoryCard.ENTITY_DESPUES_REQUERIDO, example = "30.50")        // This annotation indicates that information for the swagger
    @Column(name = "despues", nullable = false) 
    private BigDecimal despues;

    @Column(name = "cargar_tarjeta_id", nullable = true)
    private Integer cargarTarjeta;
    
    @Column(name = "bitacora_combustible_id", nullable = true)
    private Integer bitacoraCombustible;
}
