/**
 * @author Jonathan Gilberto Diaz Reyes
 * @version 1.0.1 Modificado el 26 Feb 2025
 * @date 26/02/2025
 */
package com.example.residencia_back.entities.modules;

import java.math.BigDecimal;
import java.sql.Timestamp;

import org.hibernate.annotations.CreationTimestamp;

import com.example.residencia_back.entities.administration.User;
import com.example.residencia_back.helpers.SystemText;
import com.example.residencia_back.validator.onCreate;
import com.example.residencia_back.validator.onUpdate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a load card entity in the modules schema, mapping to the
 * "cargar_tarjeta" table.
 *
 * @param id The unique identifier of the load card record (automatically generated).
 * @param observaciones Additional observations about the load card (optional, max length: 70).
 * @param cantidad The amount of the load card transaction (required, numeric).
 * @param fechaCreacion The timestamp indicating when the load card transaction was created (automatically set).
 * @param usuario The user associated with the load card transaction (required, references User entity).
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@ToString
@Table(schema = "modulos", name = "cargar_tarjeta")
public class LoadCard {
     @Id                         // This annotation indicates that this field is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)                      // This annotation indicates that the primary key value is automatically generated by the database.
    @Schema(description = SystemText.LoadCard.ENTITY_ID, example = "1")        // This annotation indicates that information for the swagger
    @NotNull(groups = onUpdate.class, message = SystemText.LoadCard.ENTITY_ID_REQUERIDO)        // This annotation indicates that this parameter must not be null.
    @Column(name = "id")        // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private int id;

    @Schema(description = SystemText.LoadCard.ENTITY_OBSERVACIONES, example = "Observaciones adicionales")        // This annotation indicates that information for the swagger
    @Column(name = "observaciones", length = 70, nullable = false)         // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private String observaciones;

    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.LoadCard.ENTITY_CANTIDAD_REQUERIDO)         // This annotation indicates that this parameter must not be null.
    @Schema(description = SystemText.LoadCard.ENTITY_CANTIDAD, example = "30.50")        // This annotation indicates that information for the swagger
    @Column(name = "cantidad", nullable = false) 
    private BigDecimal cantidad;

     @CreationTimestamp          // This annotation indicates that the field is automatically set to the creation date and time.
    @Schema(hidden = true)      // This annotation indicates that the attribute will not be displayed in the swagger
    @Column(name = "fecha_creacion", nullable = false)       // This annotation indicates that Associates the attribute with a database column and indicates the validations it must have in order to be assigned a value.
    private Timestamp fechaCreacion;

    @OneToMany                 // This annotation indicates that Indicates that it is a foreign key
    @NotNull(groups = {onCreate.class, onUpdate.class}, message = SystemText.LoadCard.ENTITY_USUARIO_ID_REQUERIDO)       // This annotation indicates that this parameter must not be empty.
    @Schema(description = SystemText.LoadCard.ENTITY_USUARIO_ID, example = "{\"id\": 1}")        // This annotation indicates that information for the swagger
    @JoinColumn(name = "usuario_id", nullable = false, referencedColumnName = "id")
    private User usuario;
}
